### PR TITLE
RPE-848 Restructure helm repo

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by luigibk** [comment]
You think it would be worth having a generic/stable + generic/unstable instead of just generic?

**Comment by timja** [comment]
don't think we need to worry about that
helm charts community has stable vs experimental but I think we can just talk to each other?

**Comment by luigibk** [comment]
I think it could be useful to have, for some chart changes at least, a phased adoption, which is something the experimental would allow. It can also be done with versions on the other hand, even if the intent would be less clear.

**Review by luigibk — APPROVED** [review]

**Review by njrich28 — APPROVED** [review]
LGTM

**Pull request merged**
